export const RESET_TASK_COUNT = 'RESET_TASK_COUNT';
export const ADD_TASK_COUNT = 'ADD_TASK_COUNT';
export const SUBTRACT_TASK_COUNT = 'SUBTRACT_TASK_COUNT';
export const CHANGE_FILTER = 'CHANGE_FILTER';
export const TOGGLE_LOADING = 'TOGGLE_LOADING';
export const FETCH_TASKS = 'FETCH_TASKS';
